# -*- mode: shell-script; -*-

# Basic PATH so that it can be extended later depending on the platform.
basic_path=$PATH:$HOME/bin

# With this, apps using $EDITOR will use terminal emacs.
export EDITOR='emacsclient -t --alternate-editor="emacs"'
export VISUAL=$EDITOR

# I want to title my shells by myself.
export DISABLE_AUTO_TITLE=true

# Having PREFIX set makes nvm complaint about it. oh-my-zsh is doing it.
unset PREFIX

# Rubygems allows to split the configuration into different .gemrc equivalent
# files. This .gemrc_local is meant to keep the private configs, like gem
# sources which require username/password.
[[ -f $HOME/.gemrc_local ]] && export GEMRC=$HOME/.gemrc_local

# .zshrc_local is meant to keep private configurations, it is out of version
# management.
[[ -f $HOME/.zprofile_local ]] && source $HOME/.zprofile_local

export PATH=/usr/local/heroku/bin:$basic_path

# Load direnv
eval "$(direnv hook zsh)"

# Load rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# Load pebble sdk
# export PATH=$HOME/Downloads/pebble-dev/pebble-sdk-4.3-linux64/bin:$PATH

# Load rust and cargo
export PATH=$PATH:$HOME/.cargo/bin
export RUST_SRC_PATH=$HOME/Documents/src/rust/src

# Load nvm
export NVM_DIR="$HOME/.nvm"
[[ -s /usr/share/nvm/nvm.sh ]] && . /usr/share/nvm/nvm.sh

# Config for virtualenv & virtualenvwrapper
export PROJECT_HOME=$HOME/Documents/src
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
if [[ -f /usr/local/bin/virtualenvwrapper.sh ]]; then
    source /usr/local/bin/virtualenvwrapper.sh
fi
