# -*- mode: shell-script; -*-

# This file is meant to load only things which are needed on an interactive
# shell, like customizations, special aliases, etc.

# oh-my-zsh specific configuration.
export ZSH=$HOME/.oh-my-zsh
export ZSH_THEME="minimal"
plugins=(git gem rails autojump common-aliases)
source $ZSH/oh-my-zsh.sh

# Aliases
alias be='bundle exec'
alias bi='bundle install'
alias bu='bundle update'
# noglob needed for rake + zsh
alias rake='noglob bundle exec rake'
alias br='bin/rspec'
alias bs='bin/spring'
alias rspec='bundle exec rspec'
alias r='rspec'
alias e=$EDITOR
alias ec='e -c'
alias vi='e'

eval "$(hub alias -s)"

# NVM needs this to work. Some oh-my-zsh themes use it. Leaving it here just in
# case.
# unset PREFIX

export NVM_DIR="$HOME/.nvm"
[[ -s /usr/share/nvm/nvm.sh ]] && . /usr/share/nvm/nvm.sh

# Config for virtualenv & virtualenvwrapper
export PROJECT_HOME=$HOME/Documents/src
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
if [[ -f /usr/local/bin/virtualenvwrapper.sh ]]; then
    source /usr/local/bin/virtualenvwrapper.sh
fi

# Export ssh-agent socket
export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket
