---
- name: Install sudo
  pacman:
    name: sudo
    state: present

- name: Configure sudo
  lineinfile: 
    dest: /etc/sudoers.d/fran
    line: "%wheel ALL=(ALL) ALL"
    state: present
    create: yes
    validate: "visudo -cf %s"
